/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qrcodegenerator.ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import qrcodegenerator.entity.Area;
import qrcodegenerator.entity.MasterProduct;
import qrcodegenerator.entity.User;
import qrcodegenerator.service.KhususService;
import qrcodegenerator.service.ProductService;
import qrcodegenerator.service.impl.KhususServiceImpl;
import qrcodegenerator.service.impl.ProductServiceImpl;
import qrcodegenerator.utils.PrintQRCode;

/**
 *
 * @author Rizaldi Habibie
 */
public class GeneratePage extends javax.swing.JInternalFrame {
private KhususService khususService;
private PrintQRCode print = new PrintQRCode();
private Area area;
private ProductService productService;
private MasterProduct masterProduct;
private User user;
    /**
     * Creates new form GeneratePage
     */
    public GeneratePage(User user) {
        initComponents();
        this.user = user;
        chooseAreaLabel.setText("<HTML><U>Pilih Area</U></HTML>");
        chooseProductLabel.setText("<HTML><U>Pilih Barang</U></HTML>");
    }
    
    public void setMasterProduct(MasterProduct masterProduct){
        this.masterProduct = masterProduct;
        productCodeField.setText(masterProduct.getKodeBarang());
        productNameField.setText(masterProduct.getNamaBarang());
        clientField.setText(masterProduct.getClient());
        specialNumberField.setText(masterProduct.getSpecialNumber());
        typeField.setText(masterProduct.getType());
        totalField.setText(""+masterProduct.getJumlah());
        
    }

    public JTextField getAreaField() {
        return areaField;
    }

    public void setAreaField(JTextField areaField) {
        this.areaField = areaField;
    }

    public JTextField getClientField() {
        return clientField;
    }

    public void setClientField(JTextField clientField) {
        this.clientField = clientField;
    }

    public JButton getGenerateButton() {
        return generateButton;
    }

    public void setGenerateButton(JButton generateButton) {
        this.generateButton = generateButton;
    }

    public JTextField getProductCodeField() {
        return productCodeField;
    }

    public void setProductCodeField(JTextField productCodeField) {
        this.productCodeField = productCodeField;
    }

    public JTextField getProductNameField() {
        return productNameField;
    }

    public void setProductNameField(JTextField productNameField) {
        this.productNameField = productNameField;
    }

    public JTextField getSpecialNumberField() {
        return specialNumberField;
    }

    public void setSpecialNumberField(JTextField specialNumberField) {
        this.specialNumberField = specialNumberField;
    }

    public JTextField getTotalField() {
        return totalField;
    }

    public void setTotalField(JTextField totalField) {
        this.totalField = totalField;
    }

    public JTextField getTotalSheetField() {
        return totalSheetField;
    }

    public void setTotalSheetField(JTextField totalSheetField) {
        this.totalSheetField = totalSheetField;
    }

    public JTextField getTypeField() {
        return typeField;
    }

    public void setTypeField(JTextField typeField) {
        this.typeField = typeField;
    }

    public JLabel getChooseAreaLabel() {
        return chooseAreaLabel;
    }

    public void setChooseAreaLabel(JLabel chooseAreaLabel) {
        this.chooseAreaLabel = chooseAreaLabel;
    }

    public JLabel getChooseProductLabel() {
        return chooseProductLabel;
    }

    public void setChooseProductLabel(JLabel chooseProductLabel) {
        this.chooseProductLabel = chooseProductLabel;
    }
    
    public void empty(){
        productCodeField.setText("");
        productNameField.setText("");
        clientField.setText("");
        specialNumberField.setText("");
        typeField.setText("");
        areaField.setText("");
        totalField.setText("");
        area = null;
        masterProduct = null;
        totalSheetField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        productNameField = new javax.swing.JTextField();
        clientField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        specialNumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        productCodeField = new javax.swing.JTextField();
        areaField = new javax.swing.JTextField();
        chooseProductLabel = new javax.swing.JLabel();
        chooseAreaLabel = new javax.swing.JLabel();
        totalSheetField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Generate And Print");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        productNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(productNameField, gridBagConstraints);

        clientField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(clientField, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setText("Nama Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 21, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Klien");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        specialNumberField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(specialNumberField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Nomor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Jenis / Merk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        typeField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(typeField, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Area");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        totalField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(totalField, gridBagConstraints);

        generateButton.setBackground(new java.awt.Color(51, 51, 51));
        generateButton.setForeground(new java.awt.Color(255, 255, 255));
        generateButton.setText("GENERATE");
        generateButton.setMaximumSize(new java.awt.Dimension(85, 20));
        generateButton.setMinimumSize(new java.awt.Dimension(85, 20));
        generateButton.setPreferredSize(new java.awt.Dimension(85, 20));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 19, 0);
        jPanel1.add(generateButton, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Kode Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        productCodeField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 0);
        jPanel1.add(productCodeField, gridBagConstraints);

        areaField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(areaField, gridBagConstraints);

        chooseProductLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chooseProductLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/images/Button-Add-icon.png"))); // NOI18N
        chooseProductLabel.setText("Pilih Barang");
        chooseProductLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 0, 11);
        jPanel1.add(chooseProductLabel, gridBagConstraints);

        chooseAreaLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chooseAreaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qrcodegenerator/images/Button-Add-icon.png"))); // NOI18N
        chooseAreaLabel.setText("Pilih Area");
        chooseAreaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(chooseAreaLabel, gridBagConstraints);

        totalSheetField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(totalSheetField, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setText("Jumlah Sheet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 20, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
//        
//        if(masterProduct == null){
//         masterProduct = new MasterProduct();
//         masterProduct.setKodeBarang(productCodeField.getText());
//         masterProduct.setNamaBarang(productNameField.getText());
//         masterProduct.setClient(clientField.getText());
//         masterProduct.setSpecialNumber(specialNumberField.getText());
//         masterProduct.setType(typeField.getText());
//         masterProduct.setJumlah(Integer.parseInt(totalField.getText()));
//         productService = new ProductServiceImpl();
//         productService.addProduct(masterProduct);
//        }
//        khususService = new KhususServiceImpl();
//        
//        print.generateNewQRCode(masterProduct, area,user, Integer.parseInt(totalSheetField.getText()));
//        empty();
    }//GEN-LAST:event_generateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaField;
    private javax.swing.JLabel chooseAreaLabel;
    private javax.swing.JLabel chooseProductLabel;
    private javax.swing.JTextField clientField;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField productCodeField;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField specialNumberField;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField totalSheetField;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
