package qrcodegenerator.entity;
// Generated Jul 11, 2016 8:16:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {
     private Integer noUrut;
     private String kodeArea;
     private String namaArea;

    public Area() {
    }

    public Area(String kodeArea, String namaArea) {
       this.kodeArea = kodeArea;
       this.namaArea = namaArea;
    }
   
    public Integer getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(Integer noUrut) {
        this.noUrut = noUrut;
    }
    public String getKodeArea() {
        return this.kodeArea;
    }
    
    public void setKodeArea(String kodeArea) {
        this.kodeArea = kodeArea;
    }
    public String getNamaArea() {
        return this.namaArea;
    }
    
    public void setNamaArea(String namaArea) {
        this.namaArea = namaArea;
    }




}


