package qrcodegenerator.entity;
// Generated Jul 11, 2016 8:16:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Khusus generated by hbm2java
 */
public class Khusus  implements java.io.Serializable {


     private Integer noUrut;
     private MasterProduct masterProduct;
     private Area area;
     private Sheet sheet;
     private String kodeUnik;
     private String qrcodeNumerator;
     private String status;
     private Date tanggalCetakPertama;
     private User user;

    public Khusus() {
    }

	
    public Khusus(MasterProduct masterProduct) {
        this.masterProduct = masterProduct;
    }
    public Khusus(MasterProduct masterProduct, Integer noUrutArea, Sheet sheet, String kodeUnik, String qrcodeNumerator, String status, Date tanggalCetakPertama, User user) {
       this.masterProduct = masterProduct;
       this.area = area;
       this.sheet = sheet;
       this.kodeUnik = kodeUnik;
       this.qrcodeNumerator = qrcodeNumerator;
       this.status = status;
       this.tanggalCetakPertama = tanggalCetakPertama;
       this.user= user;
    }
   
    public Integer getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(Integer noUrut) {
        this.noUrut = noUrut;
    }
    public MasterProduct getMasterProduct() {
        return this.masterProduct;
    }
    
    public void setMasterProduct(MasterProduct masterProduct) {
        this.masterProduct = masterProduct;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area= area;
    }
    public Sheet getSheet() {
        return this.sheet;
    }
    
    public void setSheet(Sheet sheet) {
        this.sheet = sheet;
    }
    public String getKodeUnik() {
        return this.kodeUnik;
    }
    
    public void setKodeUnik(String kodeUnik) {
        this.kodeUnik = kodeUnik;
    }
    public String getQrcodeNumerator() {
        return this.qrcodeNumerator;
    }
    
    public void setQrcodeNumerator(String qrcodeNumerator) {
        this.qrcodeNumerator = qrcodeNumerator;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getTanggalCetakPertama() {
        return this.tanggalCetakPertama;
    }
    
    public void setTanggalCetakPertama(Date tanggalCetakPertama) {
        this.tanggalCetakPertama = tanggalCetakPertama;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


