package qrcodegenerator.entity;
// Generated Jul 11, 2016 8:16:11 AM by Hibernate Tools 3.2.1.GA



/**
 * MasterProduct generated by hbm2java
 */
public class MasterProduct  implements java.io.Serializable {


     private Integer noUrut;
     private String kodeBarang;
     private String namaBarang;
     private String client;
     private String type;
     private int jumlah;
     private String specialNumber;

    public MasterProduct() {
    }

    public MasterProduct(String kodeBarang, String namaBarang, String client, String type, int jumlah, String specialNumber) {
       this.kodeBarang = kodeBarang;
       this.namaBarang = namaBarang;
       this.client = client;
       this.type = type;
       this.jumlah = jumlah;
       this.specialNumber = specialNumber;
    }
   
    public Integer getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(Integer noUrut) {
        this.noUrut = noUrut;
    }
    public String getKodeBarang() {
        return this.kodeBarang;
    }
    
    public void setKodeBarang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }
    public String getSpecialNumber() {
        return this.specialNumber;
    }
    
    public void setSpecialNumber(String specialNumber) {
        this.specialNumber = specialNumber;
    }




}


