package qrcodegenerator.entity;
// Generated Jul 11, 2016 8:16:11 AM by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer noUrut;
     private String kodeUser;
     private String namaUser;
     private String username;
     private String password;
     private String bagian;

    public User() {
    }

    public User(String kodeUser, String namaUser, String username, String password, String bagian) {
       this.kodeUser = kodeUser;
       this.namaUser = namaUser;
       this.username = username;
       this.password = password;
       this.bagian = bagian;
    }
   
    public Integer getNoUrut() {
        return this.noUrut;
    }
    
    public void setNoUrut(Integer noUrut) {
        this.noUrut = noUrut;
    }
    public String getKodeUser() {
        return this.kodeUser;
    }
    
    public void setKodeUser(String kodeUser) {
        this.kodeUser = kodeUser;
    }
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getBagian() {
        return this.bagian;
    }
    
    public void setBagian(String bagian) {
        this.bagian = bagian;
    }




}


